// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"database/sql"
)

// i18n语言键
type BladeI18nKey struct {
	// id
	ID int64
	// 消息终端id
	TerminalID int64
	// 0-字符串 1-富文本
	DataType int8
	// 编码
	Code string
	// 名称
	Name string
	// 创建人
	CreateUser sql.NullInt64
	// 创建时间
	CreateTime sql.NullTime
	// 修改人
	UpdateUser sql.NullInt64
	// 修改时间
	UpdateTime sql.NullTime
	// 创建部门
	CreateDept sql.NullInt64
	// 状态
	Status sql.NullInt32
	// 是否已删除
	IsDeleted sql.NullInt32
}

// i18n语言定义
type BladeI18nLanguage struct {
	// id
	ID int64
	// 编码
	Code sql.NullString
	// 名称
	Name sql.NullString
	// 0-否 1-是   是否系统默认语种
	IsDefault int8
	// 创建人
	CreateUser sql.NullInt64
	// 创建时间
	CreateTime sql.NullTime
	// 修改人
	UpdateUser sql.NullInt64
	// 修改时间
	UpdateTime sql.NullTime
	// 是否已删除
	IsDeleted sql.NullInt32
	// 状态
	Status sql.NullInt32
	// 创建部门
	CreateDept sql.NullInt64
}

// i18n语言终端
type BladeI18nTerminal struct {
	// id
	ID int64
	// 父终端id
	ParentID sql.NullInt64
	// 编码
	Code sql.NullString
	// 名称
	Name sql.NullString
	// 创建人
	CreateUser sql.NullInt64
	// 创建时间
	CreateTime sql.NullTime
	// 修改人
	UpdateUser sql.NullInt64
	// 修改时间
	UpdateTime sql.NullTime
	// 创建部门
	CreateDept sql.NullInt64
	// 状态
	Status sql.NullInt32
	// 是否已删除
	IsDeleted sql.NullInt32
}

// i18n语言值
type BladeI18nValue struct {
	// id
	ID int64
	// 语言定义id
	DefinitionID sql.NullInt64
	// 语言键id
	KeyID sql.NullInt64
	// 键值
	Value sql.NullString
	// 创建人
	CreateUser sql.NullInt64
	// 创建时间
	CreateTime sql.NullTime
	// 修改人
	UpdateUser sql.NullInt64
	// 修改时间
	UpdateTime sql.NullTime
	// 创建部门
	CreateDept sql.NullInt64
	// 状态
	Status sql.NullInt32
	// 是否已删除
	IsDeleted sql.NullInt32
}
