// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: blade_i18n_terminal.sql

package repository

import (
	"context"
	"database/sql"
	"strings"
)

const selectI18nByLangAndKey = `-- name: SelectI18nByLangAndKey :one
select ilk.code as 'key',
    ilv.value,
    ilk.data_type
from blade_i18n_language ild
    join blade_i18n_value ilv
on ild.id = ilv.definition_id
    join blade_i18n_key ilk on ilk.id = ilv.key_id
    join blade_i18n_terminal ilt on ilk.terminal_id = ilt.id
where ild.is_deleted = 0
  and ild.status = 1
  and ilv.is_deleted = 0
  and ilv.status = 1
  and ilk.is_deleted = 0
  and ilk.status = 1
  and ilt.is_deleted = 0
  and ild.code = ?
  and ilk.code = ?
  and ilt.code IN (/*SLICE:terminal_codes*/?)
limit 1
`

type SelectI18nByLangAndKeyParams struct {
	Lang          sql.NullString
	Key           string
	TerminalCodes []sql.NullString
}

type SelectI18nByLangAndKeyRow struct {
	Key      string
	Value    sql.NullString
	DataType int8
}

func (q *Queries) SelectI18nByLangAndKey(ctx context.Context, arg SelectI18nByLangAndKeyParams) (SelectI18nByLangAndKeyRow, error) {
	query := selectI18nByLangAndKey
	var queryParams []interface{}
	queryParams = append(queryParams, arg.Lang)
	queryParams = append(queryParams, arg.Key)
	if len(arg.TerminalCodes) > 0 {
		for _, v := range arg.TerminalCodes {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:terminal_codes*/?", strings.Repeat(",?", len(arg.TerminalCodes))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:terminal_codes*/?", "NULL", 1)
	}
	row := q.db.QueryRowContext(ctx, query, queryParams...)
	var i SelectI18nByLangAndKeyRow
	err := row.Scan(&i.Key, &i.Value, &i.DataType)
	return i, err
}

const selectLanguageTerminalByCode = `-- name: SelectLanguageTerminalByCode :one
SELECT id,
    parent_id,
    code,
    name,
    create_user,
    create_time,
    update_user,
    update_time,
    create_dept,
    status,
    is_deleted
FROM blade_i18n_terminal
WHERE code = ?
  AND is_deleted = 0
LIMIT 1
`

func (q *Queries) SelectLanguageTerminalByCode(ctx context.Context, code sql.NullString) (BladeI18nTerminal, error) {
	row := q.db.QueryRowContext(ctx, selectLanguageTerminalByCode, code)
	var i BladeI18nTerminal
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.Code,
		&i.Name,
		&i.CreateUser,
		&i.CreateTime,
		&i.UpdateUser,
		&i.UpdateTime,
		&i.CreateDept,
		&i.Status,
		&i.IsDeleted,
	)
	return i, err
}

const selectLanguageTerminalByParentId = `-- name: SelectLanguageTerminalByParentId :many
SELECT id,
    parent_id,
    code,
    name,
    create_user,
    create_time,
    update_user,
    update_time,
    create_dept,
    status,
    is_deleted
FROM blade_i18n_terminal
WHERE parent_id = ?
  AND is_deleted = 0
`

func (q *Queries) SelectLanguageTerminalByParentId(ctx context.Context, parentID sql.NullInt64) ([]BladeI18nTerminal, error) {
	rows, err := q.db.QueryContext(ctx, selectLanguageTerminalByParentId, parentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BladeI18nTerminal
	for rows.Next() {
		var i BladeI18nTerminal
		if err := rows.Scan(
			&i.ID,
			&i.ParentID,
			&i.Code,
			&i.Name,
			&i.CreateUser,
			&i.CreateTime,
			&i.UpdateUser,
			&i.UpdateTime,
			&i.CreateDept,
			&i.Status,
			&i.IsDeleted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
